- hosts: all
  become: true
  remote_user: root

  vars_files:
    - group_vars/vault_vars.yml
    - group_vars/datadog.yml

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600

  tasks:
    - name: Start docker container
      docker_container:
        name: redmine
        image: redmine
        state: started
        auto_remove: yes
        pull: yes
        ports:
          - 80:3000
        env:
          REDMINE_DB_PASSWORD: "{{ redmine_db_password }}"
          REDMINE_DB_USERNAME: "{{ redmine_db_username }}"
          REDMINE_DB_PORT: "{{ redmine_db_port }}"
          REDMINE_DB_POSTGRES: "{{ redmine_db_postgres }}"
          REDMINE_DB_DATABASE: "{{ redmine_db_database }}"

  roles:
    - geerlingguy.pip
    - datadog.datadog
