datadog_site: datadoghq.com
datadog_checks:
  http_check:
    init_config: null
    instances:
      - name: Application health check status
        url: 'http://localhost:80'
        timeout: 5
        method: GET
